# @desc ESLint configration
# @changed 2019.09.02, 12:16
#
# @see:
# - https://eslint.org/docs/rules/
# - https://eslint.org/docs/user-guide/configuring#specifying-environments

parser: 'babel-eslint'
extends:
  # - 'airbnb'
  - 'eslint:recommended'
plugins:
  - 'react'
  # - 'react-hooks'
env:
  browser: true
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  # react-hooks/rules-of-hooks: 'error'
  # react-hooks/exhaustive-deps: 'warn'
  no-case-declarations: 0
  consistent-return: 0
  react/sort-comp: 0
  prefer-template: 0
  brace-style: 0
  operator-linebreak: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-first-prop-new-line: 0
  object-curly-newline: 0
  class-methods-use-this: 0
  spaced-comment: 0
  arrow-body-style: 0
  padded-blocks: 0
  react/destructuring-assignment: 0
  import/prefer-default-export: 0
  no-unused-vars:
    - 'warn'
    -
      vars: 'local'
      varsIgnorePattern: '^_'
  require-jsdoc: 0
  max-len: 0
  react/prop-types: 0
  requireSemicolons: 0
  semi:
    - 'warn'
    - 'never'
  no-shadow: 0
  react/no-did-update-set-state: 0
  react/jsx-tag-spacing: 0
  no-console: 0
  # no-console: 'warn'
  no-debugger: 'warn'
  no-param-reassign: 0
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'
  react/no-unused-state: 0
  no-trailing-spaces:
    - 2
    -
      skipBlankLines: true
  jsx-a11y/label-has-for: 0
  jsx-a11y/label-has-associated-control: 0
  # linebreak-style: [2, 'unix']
overrides:
  -  # default js
    files: '**/*.{js,jsx}'
    env:
      browser: true
      commonjs: true
      es6: true
      node: true
    # globals:
    #   process: true
